using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace odev_05.Entity
{
    public class DataInitializer : DropCreateDatabaseIfModelChanges<DataContext>
    {
        protected override void Seed(DataContext context)
        {
            var kategoriler = new List<Category>()
            {
                new Category() {Name="İTHAKİ YAYINLARI",Description="İTHAKİ YAYINLARI"},
                new Category() {Name="CAN YAYINLARI",Description="CAN YAYINLARI"},
                new Category() {Name="YAPI KREDİ YAYINLARI",Description="YAPI KREDİ YAYINLARI"},
                new Category() {Name="SEL YAYINLARI",Description="SEL YAYINLARI"},
                new Category() {Name="TÜRKİYE İŞ BANKASI YAYINLARI",Description="TÜRKİYE İŞ BANKASI YAYINLARI"}
            };
            foreach (var kategori in kategoriler)
            {
                context.Categories.Add(kategori);
            }
            context.SaveChanges();

            var urunler = new List<product>()
            {
                new product() {Name="Otomatik Portakal",Author="Anthony Burgess",Page=168,Description="Tüm hayvanların en zekisi, iyiliğin ne demek olduğunu bilen insanoğluna bir baskı yöntemi uygulayarak onu otomatik işleyen bir makine haline getirenlere kılıç kadar keskin olan kalemimle saldırmaktan başka hiçbir şey yapamıyorum…” Karabasan gibi bir gelecek atmosferi… Geceleyin sokakları terörize eden, yaşamları şiddet üzerine kurulu gençler ve bu hikâyenin anti-kahramanı Alex... Yayımlandığı günden bu yana “kült roman” özelliğini kaybetmeyen Otomatik Portakal’ın 15 yaşındaki kahramanı, “iyi ya da kötü nedir?”, “İnsan özgür iradesiyle kaderini seçebilir mi?” gibi soruların yanıtlarını kurcalarken, şiddet dolu sahnelere Beethoven’ın, Mozart’ın müziği eşlik ediyor; Alex ve “çete kardeşleri” Pete, Georgie ve Aptalof, yarattıkları yepyeni dilin kelimelerini okurun zihnine kazıyorlar. Ünlü yönetmen Stanley Kubrick tarafından 1971’de filme de çekilen Otomatik Portakal tüm zamanların en sarsıcı romanlarından. “Cockney dilinde (İngiliz argosu) bir deyiş vardır. ‘Uqueer as as clockwork orange’. Bu deyiş, olabilecek en yüksek derecede gariplikleri barındıran kişi anlamına gelir. Bu çok sevdiğim lafı, yıllarca bir kitap başlığında kullanmayı düşünmüşümdür. Bir de tabii Malezya’da ‘canlı’ anlamına gelen ‘orang’ sözcüğü var. Kitabı yazmaya başladığımda, rengi ve kokusu hoş bir meyvenin kullanıldığı bu deyişin, tam da anlatmak istediğim duruma, Pavlov kanunlarının uygulanmasına dayalı bir hikâyeye çok iyi oturduğunu düşündüm.” Anthony Burgess",Price=9.99 ,Stock=100,IsHome=true,IsApproved=true,IsFeatured=false,Slider=true,CategoryId=5,Date="10.09.2019",Image="1.jpg",Language="TÜRKÇE",PaperType="Kitap Kağıdı",Size="12.5 x 20.5 cm",LittleDescription="Karabasan gibi bir gelecek atmosferi... Geceleyin sokaklara dehşet saçan, yaşamları şiddet üzerine kurulu gençler... Sosyal kehanet? Kara mizah? Özgür iradenin irdelenişi?.. Otomatik portakal bunların hepsidir. " ,Translater="Dost Körpe",image2="1.jpg"},
                new product() {Name="Fahrenheit 451",Author="Ray Bradbury",Page=202,LittleDescription="Çok eskiden itfayecilerin yangınları başlatmak yerine söndürdüğü doğru mu?",Price=15.38 ,Stock=100,IsHome=true,IsApproved=true,IsFeatured=true,Slider=false,CategoryId=1,Image="2.jpg",Date="20.08.2021",Language="TÜRKÇE",PaperType="Kitap Kağıdı",Size="13.5 x 21 cm",Translater="Dost Körpe",Description="ABD’li yazar Ray Bradbury tarafından yazılan Fahrenheit 451 kitabının odak noktasında bir itfaiye eri olan Guy Montag yer alır. Yazarın distopik kurgusunda “Geleceğin Amerikası” olarak resmettiği dünya, bir hayli karanlık görünür. Çünkü bu evrende insanları bilinçlendiren, geliştiren tüm kitaplar, büyük bir tehlike olarak görülür. İtfaiye eri Montag’ın ve çalışma arkadaşlarının görevi tüm kitapları yakmak ve ortadan yok etmektir. İtfaiyeciler bu evrende yangınları yok eden değil, yangınları meydana getiren kişilerdir. Kitapların yakılmasıyla otoriteye karşı çıkacak, bilgili insanların engellenmesi amaçlanır. Toplumda skolastik düşüncenin etkisi ve ağırlığı iyiden iyiye yoğunlaşır. Montag işine öyle odaklanmıştır ki kitapları neden yaktıklarını dahi uzunca bir süre sorgulamaz. Ta ki günün birinde Clairese isimli genç ve akıllı bir kızla tanışıncaya dek…" ,image2="2.jpg"},
                new product() {Name="1984",Author="George Orwel",Language="TÜRKÇE",PaperType="Kitap Kağıdı",Page=350,LittleDescription="Sovyet Rusya’ya bir eleştiri niteliğinde olan bu kitap, günümüz siyasetinin baskısı, toplumdaki adaletsizliği, insanların tek tipleştirilmek istenmesi, zihnin kontrolü ve bireyselliğin yok edilmesi gibi kavramlar üzerinde de duruyor. Ütopik olduğu kadar gerçekçi yönlere de yer veren roman, sizi yaşadığınız toplum düzeni içerisinde de düşünmeye davet ediyor. Önlem alınmadığı takdirde nerelere sürüklenebileceğimiz konusunda ipuçları veren bu romanı, elinizden bırakamayacaksınız.",Price=20.89 ,Stock=150,IsHome=true,IsApproved=true,IsFeatured=true,Slider=true,CategoryId=2,Image="3.jpg",Translater="Celal Üster",Date="25.04.2019",Size="12.5 x 19.5 cm",Description="Parti’nin dünya görüşü, onu hiç anlayamayan insanlara çok daha kolay dayatılıyordu. Her şeyi yutuyorlar ve hiçbir zarar görmüyorlardı çünkü tıpkı bir mısır tanesinin bir kuşun bedeninden sindirilmeden geçip gitmesi gibi, yuttuklarından geriye bir şey kalmıyordu.George Orwell’in kült kitabı Bin Dokuz Yüz Seksen Dört, yazarın geleceğe ilişkin bir kâbus senaryosudur. Bireyselliğin yok edildiği, zihnin kontrol altına alındığı, insanların makineleşmiş kitlelere dönüştürüldüğü totaliter bir dünya düzeni, romanda inanılmaz bir hayal gücüyle, en ince ayrıntısına kadar kurgulanmıştır. Geçmişte ve günümüzde dünya sahnesinde tezgâhlanan oyunlar düşünüldüğünde, ütopik olduğu kadar gerçekçi bir romandır Bin Dokuz Yüz Seksen Dört. Güncelliğini hiçbir zaman yitirmeyen bir başyapıttır; yalnızca yarına değil, bugüne de ilişkin bir uyarı çığlığıdır. ",image2="3.jpg"},
                new product() {Name="Fareler ve Insanlar",Language="TÜRKÇE",PaperType="Kitap Kağıdı",Author="John Steinbeck",Page=126,LittleDescription="Fareler ve İnsanlar, birbirine zıt karakterdeki iki mevsimlik tarım işçisinin, zeki George Milton ve onun güçlü kuvvetli ama akli dengesi bozuk yoldaşı Lennie Small’un öyküsünü anlatır.",Price=14.55 ,Stock=110,IsHome=true,IsApproved=true,IsFeatured=false,Slider=true,CategoryId=4,Image="4.jpg",Size="13.5 x 19.5",Translater="Ayşe Ece",Date="21.05.2020",Description="Pulitzer ve Nobel Edebiyat Ödülü’nü kazanan John Steinbeck’in çağımızın toplumsal ve insani meselelerini ustalıkla resmettiği eserleri modern dünya edebiyatının başyapıtları arasında yer alır. Steinbeck romanlarında yalın ve keskin bir gerçeklik sunarken yine de her seferinde çarpıcı bir öykü ile çıkar okurunun karşısına. Tarihin bir kesitindeki dramı insani ayrıntıları kaçırmadan sergilerken, *tozpembe olmayan gerçekçi bir umudun* türküsünü dillendirir. Bu nedenle eserleri edebi değerleri kadar güncelliklerini de hiç yitirmemiştir.Fareler ve İnsanlar, birbirine zıt karakterdeki iki mevsimlik tarım işçisinin, zeki George Milton ve onun güçlü kuvvetli ama akli dengesi bozuk yoldaşı Lennie Small’un öyküsünü anlatır. Küçük bir toprak satın alıp insanca bir hayat yaşamanın hayalini kuran bu ikilinin öyküsünde dostluk ve dayanışma duygusu önemli bir yer tutar. Steinbeck insanın insanla ilişkisini anlatmakla kalmaz insanın doğayla ve toplumla kurduğu ilişkileri de konu eder bu destansı romanında. Kitabın ismine ilham veren Robert Burns şiirindeki gibi; *En iyi planları farelerin ve insanların / Sıkça ters gider...*" ,image2="4.jpg" },
                new product() {Name="YerAltından Notlar ",Language="TÜRKÇE",PaperType="Kitap Kağıdı",Author="Fyodor Mihayloviç Dostoyevski",Page=139,LittleDescription="Yeraltından notlar gerçek dünyadan kendini soyutlamış bir kişinin iç çatışmalarını ve hezeyanlarını konu alır.",Price= 7.89 ,Stock=150,IsHome=true,IsApproved=true,IsFeatured=true,Slider=true,CategoryId=5,Image="5.jpg",Date="19.09.2019",Translater="Nihal Yalaza Taluy",Size="13 x 19.5 cm",Description="Fyodor Mihayloviç Dostoyevski (1821-1881 ): İlk roman İnsancıklar'ın çarpıcı konusu ve farklı kurgusuyla dikkatleri çekti.İnsan ruhunun derinliklerini sergileyiş gücüyle önemli bir yazar olarak ün kazandı.Ancak daha sonra yayımlanan eseri o dönemde fazla ilgi görmedi. Dostoyevski 1849'da 1.Nikolay'ın baskıcı rejimine muhalif Petraşevski grubunu üyesi olduğu gerekçesiyle tutuklandı.Kurşuna dizilmek üzereyken cezası sürgün ve zorunlu askerliğe çevrildi.Sibirya sürgününden sonra yazdığı romanlarla tekrar eski ününe kavuştu.1864'de Vremya dergisinde yayımladığı Yeraltından Notlar gerçek dünyadan kendini soyutlamış bir kişinin iç çatışmalarını ve hezeyanlarını konu alır.Bu roman Dostoyevski'nin daha sonra yazacağı büyük romanların ipuçlarını taşımaktadır.",image2="5.jpg"},
            };
            foreach (var urun in urunler)
            {
                context.Products.Add(urun);
            }
            context.SaveChanges();
            base.Seed(context);
        }
    }
}